openapi: 3.0.3
info:
  title: Zincwork Partner API (Staging – Full)
  version: "2.0.0-staging"
  description: |
    Full OpenAPI specification for Zincwork Partner API based on official documentation
    (https://docs.zincwork.com) and observed staging behavior.

servers:
  - url: https://stagingapi.zincwork.com

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: API_KEY

  schemas:
    Candidate:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string

    Package:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    CreateCheckRequest:
      type: object
      required: [package, candidate, resultsCallbackURL]
      properties:
        package:
          type: string
        candidate:
          $ref: "#/components/schemas/Candidate"
        resultsCallbackURL:
          type: string
          format: uri
        external_id:
          type: string

paths:
  /partner/v2/packages:
    get:
      summary: List packages
      responses:
        "200":
          description: OK

  /partner/v2/checks:
    post:
      summary: Create check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCheckRequest"
      responses:
        "200":
          description: Created
